### ISSUE TITLE
Default memory requests/limits on controller are too low

### ISSUE THREAD

**Issue by sudermanjr** [redskyops/k8s-experiment#25]
On a recent run of init, I noticed the controller pod was getting OOMKilled repeatedly.  Here's a top of the pod right now:

```
redsky-controller-manager-686bff4769-m27qw   55m          63Mi
```

 I think the defaults were 20/30Mi, which is well below that usage.

**Comment by jgustie** [comment]
We bumped the memory for the upcoming 1.3.0 release, 100Mi with a guaranteed QoS.
